# Generated by Django 5.1.2 on 2024-10-22 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_myuser_arrangement_delete_workarrangement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='arrangement',
            field=models.CharField(choices=[('full-time', 'Full-time'), ('intern', 'Intern'), ('attachee', 'Attachee')], default='full-time', max_length=50),
        ),
    ]
