# Generated by Django 5.1.2 on 2024-10-22 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_myuser_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='is_hr',
            new_name='is_manager',
        ),
    ]
